version: '3.7'

services:
  create-react-app:
    build: .
    container_name: 'create-react-app'
    environment:
      - REACT_APP_API_HOST=http://localhost:5000
    init: true
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:rw,cached
      - /usr/src/app/node_modules
    command: 'yarn start'